#!/bin/bash

curl -X 'PUT' \
  'https://socialcompass.goto.ucsd.edu/location/the-world' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "private_code": "some random string here",
  "label": "The world",
  "latitude": -25.326356,
  "longitude": 33.25622
}'