#!/bin/bash

curl -X 'DELETE' \
  'https://socialcompass.goto.ucsd.edu/location/the-world' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "private_code": "some random string here"
}'